# daemon runs in the background
# run something like tail /var/log/turtlemarinecoind/current to see the status
# be sure to run with volumes, ie:
# docker run -v $(pwd)/turtlemarinecoind:/var/lib/turtlemarinecoind -v $(pwd)/wallet:/home/turtlemarinecoin --rm -ti turtlemarinecoin:latest
FROM ubuntu:16.04

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

ADD https://github.com/just-containers/socklog-overlay/releases/download/v2.1.0-0/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

COPY . /src/turtlemarinecoin


# install build dependencies
# checkout the latest tag
# build and install
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python-dev \
      gcc-4.9 \
      g++-4.9 \
      git cmake \
      libboost1.58-all-dev \
      librocksdb-dev && \
    cd /src/turtlemarinecoin && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. && \
    make -j$(nproc) && \
    mkdir -p /usr/local/bin && \
    cp src/turtlemarinecoind /usr/local/bin/turtlemarinecoind && \
    cp src/walletd /usr/local/bin/walletd && \
    cp src/simplewallet /usr/local/bin/simplewallet && \
    cp src/miner /usr/local/bin/miner && \
    cp src/connectivity_tool /usr/local/bin/connectivity_tool && \
    strip /usr/local/bin/turtlemarinecoind && \
    strip /usr/local/bin/walletd && \
    strip /usr/local/bin/simplewallet && \
    strip /usr/local/bin/miner && \
    strip /usr/local/bin/connectivity_tool && \
    cd / && \
    rm -rf /src/turtlemarinecoin && \
    apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost1.58-all-dev librocksdb-dev && \
    apt-get autoremove -y && \
    apt-get install -y  \
      libboost-system1.58.0 \
      libboost-filesystem1.58.0 \
      libboost-thread1.58.0 \
      libboost-date-time1.58.0 \
      libboost-chrono1.58.0 \
      libboost-regex1.58.0 \
      libboost-serialization1.58.0 \
      libboost-program-options1.58.0 \
      libicu55

# setup the turtlemarinecoind service
RUN useradd -r -s /usr/sbin/nologin -m -d /var/lib/turtlemarinecoind turtlemarinecoind && \
    useradd -s /bin/bash -m -d /home/turtlemarinecoin turtlemarinecoin && \
    mkdir -p /etc/services.d/turtlemarinecoind/log && \
    mkdir -p /var/log/turtlemarinecoind && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/turtlemarinecoind/run && \
    echo "fdmove -c 2 1" >> /etc/services.d/turtlemarinecoind/run && \
    echo "cd /var/lib/turtlemarinecoind" >> /etc/services.d/turtlemarinecoind/run && \
    echo "export HOME /var/lib/turtlemarinecoind" >> /etc/services.d/turtlemarinecoind/run && \
    echo "s6-setuidgid turtlemarinecoind /usr/local/bin/turtlemarinecoind" >> /etc/services.d/turtlemarinecoind/run && \
    chmod +x /etc/services.d/turtlemarinecoind/run && \
    chown nobody:nogroup /var/log/turtlemarinecoind && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/turtlemarinecoind/log/run && \
    echo "s6-setuidgid nobody" >> /etc/services.d/turtlemarinecoind/log/run && \
    echo "s6-log -bp -- n20 s1000000 /var/log/turtlemarinecoind" >> /etc/services.d/turtlemarinecoind/log/run && \
    chmod +x /etc/services.d/turtlemarinecoind/log/run && \
    echo "/var/lib/turtlemarinecoind true turtlemarinecoind 0644 0755" > /etc/fix-attrs.d/turtlemarinecoind-home && \
    echo "/home/turtlemarinecoin true turtlemarinecoin 0644 0755" > /etc/fix-attrs.d/turtlemarinecoin-home && \
    echo "/var/log/turtlemarinecoind true nobody 0644 0755" > /etc/fix-attrs.d/turtlemarinecoind-logs

VOLUME ["/var/lib/turtlemarinecoind", "/home/turtlemarinecoin","/var/log/turtlemarinecoind"]

ENTRYPOINT ["/init"]
CMD ["/usr/bin/execlineb", "-P", "-c", "emptyenv cd /home/turtlemarinecoin export HOME /home/turtlemarinecoin s6-setuidgid turtlemarinecoin /bin/bash"]
